@echo off
REM Mermaid Diagram Conversion Script
REM Converts Mermaid diagrams to PDF and SVG formats using Docker
REM Generated by Claude

echo Converting ERD.mermaid to PDF...
docker run --rm -v %cd%:/data minlag/mermaid-cli -i docs/mermaid/ERD.mermaid -o docs/pdf/ERD.pdf -b white

echo Converting ERD.mermaid to SVG...
docker run --rm -v %cd%:/data minlag/mermaid-cli -i docs/mermaid/ERD.mermaid -o docs/img/ERD.svg -b white

echo Conversion complete!
echo - PDF: docs\pdf\ERD.pdf
echo - SVG: docs\img\ERD.svg
