spring.application.name=capstone-project
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
spring.security.oauth2.resourceserver.jwt.audiences=397977213914-2so6mkrc2o2k5n6kn1uetm3r7nqr2t8l.apps.googleusercontent.com
