spring:
  application:
    name: service

  jackson:
    deserialization:
      accept-float-as-int: false

  web:
    error:
      include-message: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://accounts.google.com"

  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB

server:
  port: 8080
  servlet:
    context-path: "/see-something"
