spring:
  application:
    name: see-something-abq

  profiles:
    active:
      - service
      - local

  datasource:
    url: "jdbc:h2:file:./db/see-something-abq"

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

storage:
  applicationHome: true
  directory: uploads
  whiteList:
    - image/jpeg
    - image/png
    - image/gif
    - image/webp
  filename:
    unknown: unknown
    format: "%1$s.%2$s"
    randomizerLimit: 0
    timestamp:
      format: "yyyyMMdd-HHmmss"
      timeZone: "UTC"
