###
POST http://localhost:8080/see-something/issue-reports
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "textDescription": "Graffiti on wall behind storefront near Central and 4th",
  "latitude": 35.0847,
  "longitude": -106.6510,
  "streetCoordinate": "Central Ave SW & 4th St SW",
  "locationDescription": "Alley wall behind the northwest corner building",
  "issueTypes": ["Trash", "Pothole"]
}

###
GET http://localhost:8080/see-something/issue-reports/mine?
    sort={{$random.alphanumeric(8)}}
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/see-something/issue-reports/mine?sort=last_modified,asc
    sort={{$random.alphanumeric(8)}}
Authorization: Bearer {{bearerToken}}


###
GET http://localhost:8080/see-something/issue-reports/mine?sort=first_reported,desc
    sort={{$random.alphanumeric(8)}}
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/see-something/issue-reports/{{externalId}}
Authorization: Bearer {{bearerToken}}

###
PUT http://localhost:8080/see-something/issue-reports/{{externalKey}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}


{
  "textDescription": "Updated description",
  "latitude": 35.0844,
  "longitude": -106.6504,
  "streetCoordinate": "Central Ave & 4th St",
  "locationDescription": "Same corner, smaller pile",
  "issueTypes": ["Trash"]
}

###
DELETE http://localhost:8080/see-something/issue-reports/{{externalKey}}
Authorization: Bearer {{bearerToken}}
