###
POST http://localhost:8080/see-something/issue-reports
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "textDescription": "adsf4 Graffiti on wall behind storefront near Central and 4th",
  "issueTypes": ["Trash", "trash"]
}

###
GET http://localhost:8080/see-something/issue-reports/mine?
    sort={{$random.alphanumeric(8)}}
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/see-something/issue-reports/mine?sort=last_modified,asc
    sort={{$random.alphanumeric(8)}}
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/see-something/issue-reports/mine?sort=first_reported,desc
    sort={{$random.alphanumeric(8)}}
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/see-something/issue-reports/11111111-1111-1111-1111-111111111005
Authorization: Bearer {{bearerToken}}

###
PUT http://localhost:8080/see-something/issue-reports/ccb97633-3ed5-46b5-881c-783d41a96a52
Content-Type: application/json
Authorization: Bearer {{bearerToken}}


{
  "textDescription": "test",
  "reportLocation": {
    "latitude": 35.0844,
    "longitude": -106.6504,
    "streetCoordinate": "Central Ave & 4th St",
    "locationDescription": "Same corner, smaller pile"
  },
  "issueTypes": ["Trash", "Pothole"],
  "reportImages": []
}

###
DELETE http://localhost:8080/see-something/issue-reports/18b6be3c-c995-4c21-9c5d-dd8af1c0a726
Authorization: Bearer {{bearerToken}}