###
GET http://localhost:8080/see-something/manager/issue-reports?
    pageSize=1&
    pageNumber=0
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

###
PUT http://localhost:8080/see-something/manager/issue-reports/{{externalId}}/issue-types
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "issueTypeTags": ["Trash"]
}

###
PUT http://localhost:8080/see-something/manager/issue-reports/{{externalId}}/status
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "statusTag": ""
}