###
GET http://localhost:8080/see-something/manager/users
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/see-something/manager/users?pageNumber=1&pageSize=2
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/see-something/manager/users/f8d87b9d-a6cb-4809-bdf8-0ec5e63d364d
Authorization: Bearer {{bearerToken}}

###
PATCH http://localhost:8080/see-something/manager/users/{{userProfileExternalId}}/enabled
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "enabled": true
}

###
PATCH http://localhost:8080/see-something/manager/users/{{userProfileExternalId}}/manager-status
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "manager": true
}