###
GET http://localhost:8080/see-something/manager/users
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/see-something/manager/users?pageNumber=1&pageSize=2
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/see-something/manager/users/{{userProfileExternalId}}
Authorization: Bearer {{bearerToken}}

###
PATCH http://localhost:8080/see-something/manager/users/{{userProfileExternalId}}/enabled
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "enabled": true
}

###
PATCH http://localhost:8080/see-something/manager/users/{{userProfileExternalId}}/manager-status
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "manager": true
}