###
POST http://localhost:8080/see-something/issue-reports/{{externalKey}}/images
Content-Type: application/json
Authorization: bearer {{bearerToken}}
Accept: application/json

{
  "imageLocator": "https://example.com/dev-images/dumped-trash-2.jpg",
  "filename": "dumped-food.jpg",
  "mimeType": "image/jpeg",
  "albumOrder": 0
}


###
GET http://localhost:8080/see-something/issue-reports/{{externalKey}}/images/{{imageId}}
Content-Type: application/json
Authorization: bearer {{bearerToken}}
Accept: application/json


###
POST http://localhost:8080/see-something/issue-reports/{{externalKey}}/images/upload
Authorization: bearer {{bearerToken}}
Content-Type: multipart/form-data; boundary=----BOUNDARY

------BOUNDARY
Content-Disposition: form-data; name="file"; filename="{{imageName.jpeg}}"
Content-Type: image/jpeg

< ./{{imageName.jpeg}}
------BOUNDARY--

###
DELETE http://localhost:8080/see-something/issue-reports/{{externalKey}}/images/{{imageId}}
Authorization: bearer {{bearerToken}}