###
GET http://localhost:8080/see-something/issue-reports/{{externalKey}}/images/{{imageId}}
Authorization: bearer {{bearerToken}}
Accept: image/jpeg


###
POST http://localhost:8080/see-something/issue-reports/{{externalKey}}/images
Authorization: bearer {{bearerToken}}
Content-Type: multipart/form-data; boundary=----BOUNDARY

------BOUNDARY
Content-Disposition: form-data; name="file"; filename="{{imageName.jpeg}}"
Content-Type: image/jpeg

< ./{{imageName.jpeg}}
------BOUNDARY--

###
DELETE http://localhost:8080/see-something/issue-reports/{{externalKey}}/images/{{imageId}}
Authorization: bearer {{bearerToken}}
