###
POST http://localhost:8080/see-something/issue-reports/11111111-1111-1111-1111-111111111006/images
Content-Type: application/json
Authorization: bearer {{bearerToken}}
Accept: application/json

{
  "imageLocator": "https://example.com/dev-images/dumped-trash-2.jpg",
  "filename": "dumped-food.jpg",
  "mimeType": "image/jpeg",
  "albumOrder": 0
}


###
GET http://localhost:8080/see-something/issue-reports/11111111-1111-1111-1111-111111111006/images/443f5865-6a07-403a-9d00-0184c03192da
Content-Type: application/json
Authorization: bearer {{bearerToken}}
Accept: application/json


###
POST http://localhost:8080/see-something/issue-reports/{{externalKey}}/images/upload
Authorization: bearer {{bearerToken}}
Content-Type: multipart/form-data; boundary=----BOUNDARY

------BOUNDARY
Content-Disposition: form-data; name="file"; filename="{{example.jpeg}}"
Content-Type: image/jpeg

C:\Users\{{user}}\deep-dive\java\projects\capstone\docs\work\{{example.jpeg}}
------BOUNDARY--