name: Checkstyle

on: [pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Reviewdog Checkstyle
      uses: dbelyaev/action-checkstyle@1df550cf7ca173631075cd649bbc52cfa6549cbd
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        level: warning
        checkstyle_config: config/checkstyle/checkstyle.xml
